export const mineSites = [
  {
    id: 'moonidih',
    name: 'Moonidih Underground Project (BCCL)',
    region: 'Western Jharia, Dhanbad',
    coordinates: [23.7428, 86.3456],
    status: 'Live monitoring',
    type: 'Deep Underground (Seam XVI)',
    leases: 48,
    gassyDegree: 'Degree III (High Methane)',
  },
  {
    id: 'gaslitand',
    name: 'Gaslitand Colliery (BCCL)',
    region: 'Katras Area IV, Dhanbad',
    coordinates: [23.7912, 86.3125],
    status: 'Operational',
    type: 'Mixed OCP / Deep Pit',
    leases: 32,
    gassyDegree: 'Degree II',
  },
  {
    id: 'kusunda',
    name: 'Kusunda Opencast Mine (BCCL)',
    region: 'Kusunda Area VI, Dhanbad',
    coordinates: [23.7745, 86.3982],
    status: 'Operational',
    type: 'Heavy Earth OCP (Fire Zone)',
    leases: 64,
    gassyDegree: 'Surface / Fire Area',
  },
  {
    id: 'lodna',
    name: 'Lodna / Jealgora Colliery (BCCL)',
    region: 'Lodna Area X, Dhanbad',
    coordinates: [23.7167, 86.4167],
    status: 'Monitored',
    type: 'Underground Coking Seam',
    leases: 28,
    gassyDegree: 'Degree II',
  },
  {
    id: 'bhelatand',
    name: 'Bhelatand Colliery (BCCL)',
    region: 'Sijua Area V, Dhanbad',
    coordinates: [23.7821, 86.3541],
    status: 'Operational',
    type: 'Underground Coking',
    leases: 36,
    gassyDegree: 'Degree II',
  },
  {
    id: 'kuya',
    name: 'Kuya Mega Opencast (BCCL)',
    region: 'Bastacolla Area IX, Dhanbad',
    coordinates: [23.7380, 86.4350],
    status: 'Live monitoring',
    type: 'Opencast Prime Coking',
    leases: 42,
    gassyDegree: 'Surface OC',
  },
];

// Dhanbad Jharia Coalfield Center Coordinates
export const indiaCenter = [23.7500, 86.4150];
export const mineCenter = [23.7428, 86.3456]; // Moonidih Deep Seam UG (Dhanbad)