import {
  ShieldCheck,
  Leaf,
  BarChart3,
  Users,
  Settings,
  Building2,
  GitBranch,
  MapPin,
  Pickaxe,
  Landmark,
  Droplets,
  Shield,
} from "lucide-react";

export const MINE_ROLES = [
  {
    id: "safety_head_officer",
    title: "Safety Head Officer",
    subtitle: "Field Safety & Compliance",
    icon: ShieldCheck,
    defaultEmail: "safety.gaslitand@nic.in",
    redirectHash: "#demo_safety_head_officer",
    levelTag: "Mine Level 2 • Gaslitand OCP",
    scopeDescription: "Katras Area • Bharat Coking Coal Limited",
  },
  {
    id: "environment_head_officer",
    title: "Environment Head Officer",
    subtitle: "Environmental Clearance & Impact",
    icon: Leaf,
    defaultEmail: "environment.gaslitand@nic.in",
    redirectHash: "#demo_environment_head_officer",
    levelTag: "Mine Level 2 • Gaslitand OCP",
    scopeDescription: "Katras Area • Bharat Coking Coal Limited",
  },
  {
    id: "production_head_officer",
    title: "Production Head Officer",
    subtitle: "Coal Extraction & Output",
    icon: BarChart3,
    defaultEmail: "production.gaslitand@nic.in",
    redirectHash: "#demo_production_head_officer",
    levelTag: "Mine Level 2 • Gaslitand OCP",
    scopeDescription: "Katras Area • Bharat Coking Coal Limited",
  },
  {
    id: "welfare_head_officer",
    title: "Welfare Head Officer",
    subtitle: "Worker Safety & Welfare",
    icon: Users,
    defaultEmail: "welfare.gaslitand@nic.in",
    redirectHash: "#demo_welfare_head_officer",
    levelTag: "Mine Level 2 • Gaslitand OCP",
    scopeDescription: "Katras Area • Bharat Coking Coal Limited",
  },
  {
    id: "mine_manager",
    title: "Mine Manager",
    subtitle: "DGMS Certified Statutory Head",
    icon: Settings,
    defaultEmail: "manager.gaslitand@nic.in",
    redirectHash: "#demo_mine_manager",
    levelTag: "Mine Level 2 • Gaslitand OCP",
    scopeDescription: "Katras Area • Bharat Coking Coal Limited",
  },
];

export const ORG_TIERS = {
  cil: {
    id: "cil",
    title: "Coal India Limited (CIL) Apex Head",
    modalTitle: "CIL Apex Command Access",
    subtitle: "Coal India Limited Headquarters",
    icon: Building2,
    defaultEmail: "cil.apex@nic.in",
    redirectHash: "#demo_cil",
    levelTag: "Apex Level 0 • New Delhi / Kolkata HQ",
    scopeDescription: "All Subsidiaries & 280+ Mining Blocks",
  },
  subsidiary: {
    id: "subsidiary",
    title: "BCCL CMD / Subsidiary Director",
    modalTitle: "Subsidiary Command Access",
    subtitle: "Bharat Coking Coal Limited (BCCL)",
    icon: GitBranch,
    defaultEmail: "cmd.bccl@coalindia.in",
    redirectHash: "#demo_subsidiary",
    levelTag: "Subsidiary Level 1 • BCCL Dhanbad",
    scopeDescription: "Bharat Coking Coal Limited Operations",
  },
  regional: {
    id: "regional",
    title: "Katras Area General Manager",
    modalTitle: "Regional Area Command Access",
    subtitle: "Katras Area Office",
    icon: MapPin,
    defaultEmail: "gm.katras@bccl.gov.in",
    redirectHash: "#demo_regional_area",
    levelTag: "Regional Level 1.5 • Katras Area",
    scopeDescription: "Katras Area Mining Leases & OCP Clusters",
  },
};

export const REGULATORY_AUTHORITIES = [
  {
    id: "dgms",
    code: "DGMS",
    title: "DGMS",
    fullName: "Directorate General of Mines Safety (DGMS)",
    roleTitle: "DGMS Statutory Safety Inspector",
    icon: Pickaxe,
    iconBg: "rgba(234, 179, 8, 0.15)",
    iconColor: "#eab308",
    defaultEmail: "dgms.inspector@nic.in",
    redirectHash: "#demo_regulatory_dgms",
    levelTag: "Regulatory Authority • DGMS",
    scopeDescription: "Mines Act 1952 Enforcement • Statutory Safety Clearance",
    department: "Directorate General of Mines Safety (DGMS), Dhanbad",
    badgeLabel: "Login for DGMS Officials",
  },
  {
    id: "ibm",
    code: "IBM",
    title: "IBM",
    fullName: "Indian Bureau of Mines",
    roleTitle: "IBM Controller of Mines / Geologist",
    icon: Landmark,
    iconBg: "rgba(56, 189, 248, 0.15)",
    iconColor: "#38bdf8",
    defaultEmail: "ibm.controller@nic.in",
    redirectHash: "#demo_regulatory_ibm",
    levelTag: "Regulatory Authority • IBM",
    scopeDescription: "Mineral Conservation & Development Rules (MCDR)",
    department: "Indian Bureau of Mines, Ministry of Mines, GoI",
    badgeLabel: "Login for IBM Officials",
  },
  {
    id: "moefcc",
    code: "MoEFCC",
    title: "MoEFCC",
    fullName: "Ministry of Environment, Forest & Climate Change",
    roleTitle: "MoEFCC Environmental Clearance Officer",
    icon: Leaf,
    iconBg: "rgba(74, 222, 128, 0.15)",
    iconColor: "#4ade80",
    defaultEmail: "moefcc.clearance@nic.in",
    redirectHash: "#demo_regulatory_moefcc",
    levelTag: "Regulatory Authority • MoEFCC",
    scopeDescription: "Environmental Clearance (EC) & Forest Diversion Compliance",
    department: "MoEFCC Impact Assessment Division, New Delhi",
    badgeLabel: "Login for MoEFCC Officials",
  },
  {
    id: "cpcb",
    code: "CPCB / SPCB",
    title: "CPCB / SPCB",
    fullName: "Central / State Pollution Control Board",
    roleTitle: "Pollution Control Board Member Secretary",
    icon: Droplets,
    iconBg: "rgba(14, 165, 233, 0.15)",
    iconColor: "#0ea5e9",
    defaultEmail: "cpcb.monitor@nic.in",
    redirectHash: "#demo_regulatory_cpcb",
    levelTag: "Regulatory Authority • CPCB / SPCB",
    scopeDescription: "Air & Water Pollution Norms • CAAQMS & Effluent Audits",
    department: "Central Pollution Control Board (CPCB), Parivesh Bhawan",
    badgeLabel: "Login for CPCB / SPCB Officials",
  },
  {
    id: "state_mining",
    code: "State Mining Authority",
    title: "State Mining Authority",
    fullName: "State Directorate of Mines & Geology",
    roleTitle: "State Directorate Mineral Officer",
    icon: Building2,
    iconBg: "rgba(168, 85, 247, 0.15)",
    iconColor: "#a855f7",
    defaultEmail: "state.mines@gov.in",
    redirectHash: "#demo_regulatory_state_mining",
    levelTag: "Regulatory Authority • State Directorate",
    scopeDescription: "State Mineral Royalty, Transit Passes & DMF Audits",
    department: "Department of Mines & Geology, State Government",
    badgeLabel: "Login for State Mining Officials",
  },
  {
    id: "other",
    code: "Other Regulatory Body",
    title: "Other Regulatory Body",
    fullName: "Other Central / State Regulatory Authorities",
    roleTitle: "Inter-Agency Mining Inspector",
    icon: Shield,
    iconBg: "rgba(244, 63, 94, 0.15)",
    iconColor: "#f43f5e",
    defaultEmail: "regulatory.auth@nic.in",
    redirectHash: "#demo_regulatory_other",
    levelTag: "Regulatory Authority • Inter-Agency",
    scopeDescription: "Revenue Intelligence, DGFT & Special Task Forces",
    department: "Central & State Regulatory Enforcement Network",
    badgeLabel: "Login for Other Regulatory Officials",
  },
];
